// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Postal_Management_System.Core.Data;

#nullable disable

namespace Postal_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Postal_Management_System.Core.Entities.Customers", b =>
                {
                    b.Property<string>("CustID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustID");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Postal_Management_System.Core.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Postal_Management_System.Core.Entities.Packages", b =>
                {
                    b.Property<string>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dest_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("PackageID");

                    b.HasIndex("TrackingID")
                        .IsUnique();

                    b.ToTable("PackageDetails", (string)null);
                });

            modelBuilder.Entity("Postal_Management_System.Core.Entities.Tracking", b =>
                {
                    b.Property<string>("TrackingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("BilledOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomBill")
                        .HasColumnType("int");

                    b.Property<string>("CustomersCustID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("custID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("declared")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrackingID");

                    b.HasIndex("CustomersCustID");

                    b.ToTable("PackageTracking", (string)null);
                });

            modelBuilder.Entity("Postal_Management_System.Core.Entities.Packages", b =>
                {
                    b.HasOne("Postal_Management_System.Core.Entities.Tracking", "Tracking")
                        .WithOne("Package")
                        .HasForeignKey("Postal_Management_System.Core.Entities.Packages", "TrackingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tracking");
                });

            modelBuilder.Entity("Postal_Management_System.Core.Entities.Tracking", b =>
                {
                    b.HasOne("Postal_Management_System.Core.Entities.Customers", null)
                        .WithMany("TrackingRecords")
                        .HasForeignKey("CustomersCustID");
                });

            modelBuilder.Entity("Postal_Management_System.Core.Entities.Customers", b =>
                {
                    b.Navigation("TrackingRecords");
                });

            modelBuilder.Entity("Postal_Management_System.Core.Entities.Tracking", b =>
                {
                    b.Navigation("Package")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
